### ISSUE TITLE
How to run Vision Visual Scripting?

### ISSUE THREAD

**Issue by StepfenShawn** [Sheriff99yt/Vision_Visual_Scripting#10]

**Comment by Sheriff99yt** [comment]
Steps to Run **V**ision **V**isual **S**cripting

1- Download and Install PyCharm https://www.jetbrains.com/pycharm/download/#section=windows
![image](https://user-images.githubusercontent.com/56188682/174562770-3f05b686-13ae-432f-87f2-3ff36127360a.png)

2- Make sure GitHub plug-in is installed

3- Click on Get From VCS 
![image](https://user-images.githubusercontent.com/56188682/174563765-9bc87a2d-2fcc-4702-89a8-8f3e08a893ce.png)

4- Copy the Link from the GitHub Repo then Past it in PyCharm then click Clone
![image](https://user-images.githubusercontent.com/56188682/174564145-62ace63c-d8f8-43ba-ae6f-424af1eaac4f.png)
![image](https://user-images.githubusercontent.com/56188682/174567314-2ed4fe15-3240-4d48-96e4-17c5dcebd533.png)

5- Go to the requirements file and make sure all necessary libraries are installed
![image](https://user-images.githubusercontent.com/56188682/174565198-33b4a8ae-e061-41d2-9ec2-064597d7fe5d.png)

6- Go to vvs_app/main.py
![image](https://user-images.githubusercontent.com/56188682/174565889-640a88ea-0cee-4f09-9c37-cf7e78391c0e.png)

7- Right click on main.py then click run
![image](https://user-images.githubusercontent.com/56188682/174566167-acce4ad6-898c-4c8a-8c49-42ce6278dbcd.png)

Finally - This is what should apear
![image](https://user-images.githubusercontent.com/56188682/175925899-a57d6ba3-dd5f-4bab-9ddf-9e4b82c0cf9e.png)


Notes:
- If you don't see run button then you need to configure a new Python interpreter environment.
https://www.youtube.com/watch?v=GTtpypvLoeY&ab_channel=PyCharmbyJetBrains

- Make sure Python is installed before doing step (**3**).
- It's better to create a new empty environment for the project to have best performance.
